from django.urls import path, re_path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import TemplateView


app_name = "catalog"
urlpatterns = [
    re_path(r"^$", views.product_list, name="product_list"),
    re_path(r"^p/(?P<slug>[^/]+)/$", views.product_detail, name="product_detail"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/add/<int:pk>/", views.cart_add_view, name="cart_add"),
    path("cart/set/<int:pk>/", views.cart_set_view, name="cart_set"),
    path("cart/remove/<int:pk>/", views.cart_remove_view, name="cart_remove"),
    path("checkout/", views.checkout, name="checkout"),
    path("fav/toggle/<int:pk>/", views.favorite_toggle, name="favorite_toggle"),
    path("favorites/", views.favorites_list, name="favorites"),
    # auth
    path("auth/login/", views.login_view, name="login"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/register/", views.register_view, name="register"),

    # account
    path("account/orders/", views.account_orders, name="account_orders"),
    path("account/profile/", views.account_profile, name="account_profile"),
    path("account/password/", views.account_password, name="account_password"),
    # catalog/urls.py
    path("auth/login-page/", views.login_page, name="login_page"),
    path("manage/",            staff_member_required(views.m_dashboard),        name="m_dashboard"),
    path("manage/products/",   staff_member_required(views.m_products),         name="m_products"),
    path("manage/products/<int:pk>/", staff_member_required(views.m_product_detail), name="m_product_detail"),
    path("manage/products/<int:pk>/toggle/", staff_member_required(views.m_product_toggle), name="m_product_toggle"),
    path("manage/products/<int:pk>/delete/", staff_member_required(views.m_product_delete), name="m_product_delete"),
    path("manage/products/<int:pk>/images/add/", staff_member_required(views.m_product_images_add), name="m_product_images_add"),
    path("manage/products/<int:pk>/images/<int:image_id>/delete/", staff_member_required(views.m_product_image_delete), name="m_product_image_delete"),
    path("cart/add/<int:pk>/ajax/", views.cart_add_ajax, name="cart_add_ajax"),
    path("manage/users/",      staff_member_required(views.m_users),            name="m_users"),
    path("manage/orders/",     staff_member_required(views.m_orders),           name="m_orders"),
    path("manage/orders/<int:pk>/status/", staff_member_required(views.m_order_status), name="m_order_status"),
     path("avtoservis/", views.autoservice_landing, name="page_avtoservis"),
    path("avtoservis-info/", views.page_about, name="page_avtoservis_info"),
    path("avtoservis-otzyvy/", TemplateView.as_view(
        template_name="static_pages/avtoservis_reviews.html"), name="page_avtoservis_reviews"),
    path("help/", views.page_help, name="page_help"),
    path("dostavka/", views.page_delivery, name="page_delivery"),
    path("oplata/", views.page_payment, name="page_payment"),
    path("brendy/", views.brands_public, name="page_brands"),
    path("marki-avto/", views.makes_public, name="page_car_makes"),
    path("dinostend/", views.page_dyno, name="page_dynostand"),
    path("kontakty/", views.page_contacts, name="page_contacts"),
    path("novosti/", views.news_list_public, name="page_news"),
    path("soglasie/", TemplateView.as_view(template_name="static_pages/soglasie.html"), name="page_agreement"),
    path("service/lead/submit/", views.service_lead_submit, name="service_lead_submit"),
    path("chip-tyuning/", views.chip_tuning_view, name="page_chip_tuning"),
    path("manage/chip/",              staff_member_required(views.m_chip_list),   name="m_chip_list"),
    path("manage/chip/<int:car_id>/", staff_member_required(views.m_chip_detail), name="m_chip_detail"),
    path("manage/chip/leads/", staff_member_required(views.m_chip_leads), name="m_chip_leads"),
    path("manage/chip/leads/<int:lead_id>/", staff_member_required(views.m_chip_lead_detail), name="m_chip_lead_detail"),
    path("manage/service/leads/", staff_member_required(views.m_service_leads), name="m_service_leads"),
    path("manage/service/leads/<int:lead_id>/", staff_member_required(views.m_service_lead_detail), name="m_service_lead_detail"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("manage/news/",                       staff_member_required(views.m_news_list),  name="m_news_list"),
    path("manage/news/new/",                   staff_member_required(views.m_news_new),   name="m_news_new"),
    path("manage/news/<int:pk>/",              staff_member_required(views.m_news_edit),  name="m_news_edit"),
    path("manage/news/<int:pk>/toggle/",       staff_member_required(views.m_news_toggle),name="m_news_toggle"),
    path("manage/news/<int:pk>/delete/",       staff_member_required(views.m_news_delete),name="m_news_delete"),
    path("manage/brands/",                         staff_member_required(views.m_brands),           name="m_brands"),
    path("manage/brands/add",                      staff_member_required(views.m_brand_add),        name="m_brand_add"),
    path("manage/brands/<int:brand_id>/logo",      staff_member_required(views.m_brand_logo),       name="m_brand_logo"),
    path("manage/brands/<int:brand_id>/delete",    staff_member_required(views.m_brand_delete),     name="m_brand_delete"),
    path("manage/brands/sync",                     staff_member_required(views.m_brands_sync),      name="m_brands_sync"),
    path("manage/makes/",                      staff_member_required(views.m_makes),        name="m_makes"),
    path("manage/makes/add",                   staff_member_required(views.m_make_add),     name="m_make_add"),
    path("manage/makes/<int:make_id>/logo",    staff_member_required(views.m_make_logo),    name="m_make_logo"),
    path("manage/makes/<int:make_id>/delete",  staff_member_required(views.m_make_delete),  name="m_make_delete"),
    path("manage/makes/sync",                  staff_member_required(views.m_makes_sync),   name="m_makes_sync"),
    path("manage/products/add/", staff_member_required(views.m_product_add), name="m_product_add"),
    path("contact/", views.contact_request_view, name="page_contact_request"),
    path("manage/contacts/", staff_member_required(views.m_contact_requests), name="m_contact_requests"),
    path("manage/contacts/<int:lead_id>/delete/", staff_member_required(views.m_contact_delete), name="m_contact_delete"),


    path("manage/categories/", staff_member_required(views.m_categories), name="m_categories"),
    path("manage/categories/add/", staff_member_required(views.m_category_add), name="m_category_add"),
    path("manage/categories/<int:cat_id>/add-child/", staff_member_required(views.m_category_add_child), name="m_category_add_child"),
    path("manage/categories/<int:cat_id>/delete/", staff_member_required(views.m_category_delete), name="m_category_delete"),
    path("manage/categories/<int:cat_id>/rename/", staff_member_required(views.m_category_rename), name="m_category_rename"),
     path("cart/badge/", views.cart_badge_count, name="cart_badge_count"), 
     path("api/filter-options/", views.api_filter_options, name="api_filter_options"),
     path("api/chip-options/", views.api_chip_options, name="api_chip_options"),
        path("manage/seo/", views.m_seo_dashboard, name="m_seo_dashboard"),

    path("manage/seo/entries/", views.m_seo_entries, name="m_seo_entries"),
    path("manage/seo/entries/new/", views.m_seo_entry_edit, name="m_seo_entry_new"),
    path("manage/seo/entries/<int:pk>/", views.m_seo_entry_edit, name="m_seo_entry_edit"),
    path("manage/seo/entries/<int:pk>/delete/", views.m_seo_entry_delete, name="m_seo_entry_delete"),
    path("account/subscribe/", views.account_subscribe, name="account_subscribe"),
    path("manage/home-latest/",                        staff_member_required(views.m_home_latest),         name="m_home_latest"),
    path("manage/home-latest/add/",                    staff_member_required(views.m_home_latest_add),     name="m_home_latest_add"),
    path("manage/home-latest/<int:pk>/toggle/",        staff_member_required(views.m_home_latest_toggle),  name="m_home_latest_toggle"),
    path("manage/home-latest/<int:pk>/delete/",        staff_member_required(views.m_home_latest_delete),  name="m_home_latest_delete"),
    path("manage/home-latest/<int:pk>/<str:dir>/",     staff_member_required(views.m_home_latest_move),    name="m_home_latest_move"),
    path("feed/google.xml", views.feed_google, name="feed_google"),
    path("feed/yml.xml",    views.feed_yml,    name="feed_yml"),
    path("manage/categories/<int:cat_id>/toggle-hidden/", views.m_category_toggle_hidden, name="m_category_toggle_hidden"),
    # path("captcha/", include("captcha.urls")),
    path("manage/robots/", views.m_robots, name="m_robots"),
    path("manage/seo/redirects/", views.m_redirects, name="m_redirects"),
    path("manage/seo/redirects/<int:pk>/delete/", views.m_redirect_delete, name="m_redirect_delete"),
    path("manage/users/mailing/", staff_member_required(views.m_users_mailing), name="m_users_mailing"),
    path("manage/seo/gone/", views.m_gone, name="m_gone"),
    path("manage/seo/gone/<int:pk>/delete/", views.m_gone_delete, name="m_gone_delete"),
    path("auth/forgot/", views.password_forgot, name="password_forgot"),
    re_path(
        r"^(?!manage/|auth/|cart/|checkout/|favorites/|news/|api/|service/|contact/|novosti/)"
        r"(?P<cat_slug>[-\w]+)/(?P<sub_slug>[-\w]+)/(?P<slug>[^/]+)/$",
        views.product_detail_by_path,
        name="product_detail_by_path",
    )
]
