# Generated by Django 5.2.5 on 2025-08-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('make', 'model', 'year', 'engine'),
                'unique_together': {('make', 'model', 'year', 'engine')},
            },
        ),
        migrations.CreateModel(
            name='ChipStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='catalog.chipcar')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('car', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChipMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('stock', models.CharField(blank=True, default='', max_length=50)),
                ('tuned', models.CharField(blank=True, default='', max_length=50)),
                ('delta', models.CharField(blank=True, default='', max_length=50)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='catalog.chipstage')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
