# Generated by Django 5.2.5 on 2025-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_chipcar_chipstage_chipmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipmetric',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена, ₽'),
        ),
    ]
