# Generated by Django 5.2.5 on 2025-08-27 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий текст')),
                ('body', models.TextField(blank=True, verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-published_at', '-id'),
            },
        ),
    ]
