# Generated by Django 5.2.5 on 2025-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'О сервисе'), ('help', 'Помощь'), ('delivery', 'Условия доставки'), ('payment', 'Условия оплаты'), ('dyno', 'Диностенд'), ('home', 'Главная')], unique=True, verbose_name='Системное имя')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, default='', verbose_name='Текст (HTML или обычный)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'страница наполнения',
                'verbose_name_plural': 'страницы наполнения',
                'ordering': ('slug',),
            },
        ),
    ]
