# Generated by Django 5.2.5 on 2025-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_cmspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home', 'Главная'), ('about', 'О сервисе'), ('help', 'Помощь'), ('delivery', 'Условия доставки'), ('payment', 'Условия оплаты'), ('dyno', 'Диностенд'), ('contacts', 'Контакты')], max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('content_html', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
