# Generated by Django 5.2.5 on 2025-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_sitepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('main-hero', 'Главный слайдер')], default='main-hero', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('link_url', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_avif', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
