# Generated by Django 5.2.5 on 2025-09-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_goneurl_redirectrule_robotstxt_seopath_seoobject'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goneurl',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='redirectrule',
            options={'ordering': ('-priority', '-id'), 'verbose_name': 'редирект', 'verbose_name_plural': 'редиректы'},
        ),
        migrations.AlterModelOptions(
            name='robotstxt',
            options={'verbose_name': 'robots.txt', 'verbose_name_plural': 'robots.txt'},
        ),
        migrations.RemoveField(
            model_name='goneurl',
            name='note',
        ),
        migrations.RemoveField(
            model_name='goneurl',
            name='path',
        ),
        migrations.RemoveField(
            model_name='redirectrule',
            name='new_url',
        ),
        migrations.RemoveField(
            model_name='redirectrule',
            name='note',
        ),
        migrations.RemoveField(
            model_name='redirectrule',
            name='old_path',
        ),
        migrations.AddField(
            model_name='goneurl',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='goneurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goneurl',
            name='is_regex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goneurl',
            name='path_or_regex',
            field=models.CharField(default=' ', max_length=400, verbose_name='Путь или regex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redirectrule',
            name='from_path',
            field=models.CharField(default=' ', max_length=400, verbose_name='Откуда (путь или regex)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redirectrule',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='redirectrule',
            name='to_url',
            field=models.CharField(default=' ', max_length=500, verbose_name='Куда (абс/отн URL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotstxt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(301, '301'), (302, '302')], default=301, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='robotstxt',
            name='content',
            field=models.TextField(default='User-agent: *\nDisallow:\n', verbose_name='robots.txt'),
        ),
        migrations.CreateModel(
            name='SEOEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('path_regex', models.CharField(blank=True, default='', max_length=400, verbose_name='Регулярка пути')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('h1', models.CharField(blank=True, default='', max_length=255, verbose_name='H1')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description')),
                ('canonical_url', models.CharField(blank=True, default='', max_length=400, verbose_name='Canonical URL')),
                ('robots_index', models.BooleanField(default=True, verbose_name='index')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='follow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO-запись',
                'verbose_name_plural': 'SEO-записи',
                'ordering': ('-updated_at', '-id'),
            },
        ),
    ]
