# Generated by Django 5.2.5 on 2025-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_goneurl_options_alter_redirectrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=120, verbose_name='Автор'),
        ),
    ]
