# Generated by Django 5.2.5 on 2025-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Мобильная картинка'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_mobile_avif',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Мобильная картинка (AVIF)'),
        ),
    ]
