# Generated by Django 5.2.5 on 2025-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_banner_image_mobile_banner_image_mobile_avif'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marketing_email',
            field=models.BooleanField(default=True, verbose_name='Согласие на e-mail рассылку'),
        ),
    ]
