# Generated by Django 5.2.5 on 2025-09-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_userprofile_marketing_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'Главная'), ('catalog', 'Каталог'), ('chip', 'Чип-тюнинг'), ('news', 'Новости')], max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='catalog.banner')),
            ],
            options={
                'ordering': ['page_key', 'position'],
                'unique_together': {('banner', 'page_key')},
            },
        ),
    ]
