# Generated by Django 5.2.5 on 2025-09-22 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_bannerplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerplacement',
            name='page_key',
            field=models.CharField(choices=[('home', 'Главная'), ('autoservice', 'Автосервис'), ('about', 'О сервисе'), ('dyno', 'Диностенд')], max_length=32),
        ),
        migrations.CreateModel(
            name='HomeLatestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_latest_items', to='catalog.product')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('product',)},
            },
        ),
    ]
