# Generated by Django 5.2.5 on 2025-10-11 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_bannerplacement_page_key_homelatestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExternalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(choices=[('sttuning', 'STTuning')], max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('parent_external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('internal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_links', to='catalog.category')),
            ],
            options={
                'unique_together': {('supplier', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(choices=[('sttuning', 'STTuning')], max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('external_sku_id', models.CharField(blank=True, max_length=64, null=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active_at_supplier', models.BooleanField(default=True)),
                ('price_retail', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_currency', models.CharField(blank=True, default='RUB', max_length=8)),
                ('stock_count_raw', models.CharField(blank=True, default='', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='catalog.product')),
            ],
            options={
                'unique_together': {('supplier', 'external_id')},
            },
        ),
    ]
