# Generated by Django 5.2.5 on 2025-10-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_categoryexternalmap_supplierproductlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(db_index=True, default='sttuning', max_length=50)),
                ('supplier_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['supplier', 'supplier_id'],
                'unique_together': {('supplier', 'supplier_id')},
            },
        ),
        migrations.CreateModel(
            name='SupplierCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(db_index=True, default='sttuning', max_length=50)),
                ('supplier_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('our_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_links_stt', related_query_name='supplier_link_stt', to='catalog.category')),
            ],
        ),
    ]
