# Generated by Django 5.2.5 on 2025-10-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
