# Generated by Django 5.2.5 on 2025-10-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_product_supplier_product_supplier_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыта'),
        ),
    ]
