# Generated by Django 5.0 on 2025-10-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_category_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_hidden_zero_price',
            field=models.BooleanField(default=False),
        ),
    ]
